"我自己的配置
" 高亮显示当前行/列
set cursorline
" vim自身命名行模式智能补全
set wildmenu
" 搜索时高亮显示被找到的文本  
set hlsearch  
" 智能自动缩进  
set smartindent  
"显示括号配对情况  
set showmatch  
"输入行高亮
set cursorline
" 设置C/C++方式自动对齐  
set autoindent  
set cindent 
"设置帮助文件为中文
set helplang=cn



"wenzq  的配置如下
set cmdheight=2
set nu
set  encoding=utf-8 
set langmenu=zh_CN.UTF-8
set ambiwidth=double 
syntax enable 
syntax on
set laststatus=2
set noundofile
set nobackup
set noswapfile
set tabstop=4   
set softtabstop=4 
set shiftwidth=4
set foldmethod=indent
set foldlevel=99

"底栏=====================================================
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}
 set statusline=[%F]%y%r%m%*%=[Line:%l/%L,Column:%c][%p%%]
 "airline options
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1
nmap <Tab> :bn<cr>
let g:airline_highlighting_cache = 0
<
 "let g:airline_theme='molokai'
 "let g:airline_theme='wombat'
  let g:airline_theme='powerlineish'
  "let g:airline_theme='qwq'
